// Synthetic responses per profile type per grade band
// Each set has responses for: reading_passage, short_response, extended_writing, reflection, scenario

type ResponseSet = Record<string, string>;

export const RESPONSES: Record<string, Record<string, ResponseSet>> = {
  "6-7": {
    thriving: {
      reading_passage: "The main tension in the passage is between people who want change and people who are worried about what change might mean. The new buildings brought jobs and a market, which is good for the town. But the text says rents went up and three stores closed, which means some people who lived there a long time might have to leave. I think both sides make good points because the town needed something new but they also need to protect the people who stayed.",
      short_response: "Last year I thought homework was pointless but then my teacher explained how practice helps your brain remember things better. She showed us this science about how memory works and I realized I was wrong. Now I actually try to do my homework because I understand why it matters, even if it's not always fun.",
      extended_writing: "My ideal school would start at 9am because I think students learn better when they're not too tired. The classrooms would have big windows and plants because nature helps people feel calm. Instead of sitting in rows, we'd have round tables so everyone can see each other and share ideas. Math would be taught through building things and solving real problems, not just worksheets. Every Friday afternoon would be for passion projects where you get to learn about whatever interests you most.",
      reflection: "When something is hard to understand, I usually read it again more slowly. If that doesn't work, I try to explain it to myself out loud, like I'm teaching someone else. Sometimes I draw a picture or diagram because seeing it helps me get it. If I'm really stuck, I'll ask my teacher or look it up online. I think the key is not giving up right away.",
      scenario: "First, I would talk to the person who hasn't done any work and ask if everything is okay. Maybe they have a reason we don't know about. Then I'd suggest we all meet and talk about what direction we want to go. If someone disagrees, we should listen to their idea and see if there's a way to combine both ideas. I think the most important thing is making sure everyone feels heard.",
    },
    developing: {
      reading_passage: "The town had mills that closed down and people left. Then some people made new buildings with businesses and a market. Some people liked it and some didn't because prices went up.",
      short_response: "I changed my mind about my little sister. I used to think she was annoying but then she helped me when I was sad and I realized she's actually nice.",
      extended_writing: "My school would have lots of recess and the food would be really good. We wouldn't have tests because tests are stressful. There would be a pool and a big library with comfy chairs. Teachers would be nice and we'd get to use computers a lot.",
      reflection: "When something is hard I usually just keep trying. Sometimes I ask my mom for help. I don't really have a specific way I do it.",
      scenario: "I would tell the teacher about the person not doing work. Then I would try to do my part and hope the others do theirs too.",
    },
    emerging: {
      reading_passage: "The town changed and some people were happy and some were not.",
      short_response: "I changed my mind about a food once. I tried it again and it was okay.",
      extended_writing: "My school would be fun. No homework. More recess. Good food.",
      reflection: "I ask for help when its hard.",
      scenario: "I would just try to do the work. If they don't help its not my fault.",
    },
  },
  "8": {
    thriving: {
      reading_passage: "River City's central tension is the classic revitalization-vs-displacement dilemma. The evidence supporting revitalization includes 40 small businesses, a farmers market, and after-school programs — concrete community infrastructure. However, the 22% property value increase and three Main Street closures show that economic growth doesn't benefit everyone equally. The text suggests this isn't a binary question: River City can be both revitalized AND displaced simultaneously, depending on whose perspective you consider.",
      short_response: "I used to believe that being good at something meant it should come easily. When I struggled with algebra, I thought I just wasn't a 'math person.' But my tutor showed me her own college math notebooks filled with crossed-out work and mistakes. Seeing that even experts struggle changed how I think about difficulty — now I see struggle as part of learning, not evidence that I can't do it.",
      extended_writing: "My ideal school would fundamentally rethink the relationship between students and time. Instead of rigid 45-minute periods, learning would happen in focused blocks of 90 minutes, with breaks built around natural attention cycles. The curriculum would integrate subjects — a project about designing a sustainable garden could cover biology, math, economics, and writing simultaneously. Assessment would be portfolio-based rather than test-based, because real learning is better demonstrated through work you build over time than answers you give under pressure. Teachers would function more as mentors, each working closely with a small group of 12 students throughout the year.",
      reflection: "My approach to difficult material follows a pattern I've noticed: first, I get frustrated and want to skip ahead. Then I force myself to go back to the last thing I understood and work forward from there. I've found that I learn best when I write things down in my own words — not copying notes, but actually restating concepts. If I can explain it simply, I understand it. If my explanation gets tangled, that's where the gap is.",
      scenario: "I'd start by privately messaging the person who hasn't contributed to check in without putting them on the spot in front of everyone. People shut down when they feel attacked. For the disagreement about direction, I'd suggest we each spend 10 minutes writing down the three strongest points for our approach, then compare. Usually the best path forward combines elements from both ideas. For the person who wants to split up — I'd acknowledge their stress but point out that our strongest work comes from building on each other's ideas.",
    },
    developing: {
      reading_passage: "The main tension is that the new businesses are good for some people but bad for others. The property values went up 22% which helps homeowners but hurts renters. Three businesses closed because of higher rent. I think the town needs to find a balance between bringing in new things and keeping old things.",
      short_response: "I changed my mind about a kid at school who I thought was mean. Turns out he was just shy and when I actually talked to him he was really nice. It taught me not to judge people before you know them.",
      extended_writing: "My ideal school would have a flexible schedule where you can choose some of your classes based on what you're interested in. There would be regular classes like math and English but also options like coding, art, and cooking. The building would have good technology but also outdoor spaces for learning. Teachers would give feedback instead of just grades so you know how to improve.",
      reflection: "When something is difficult, I usually try reading it a few times. If that doesn't work, I look for a video explanation because sometimes hearing it explained differently helps. I'm getting better at not giving up right away, but I still find it hard when I don't understand something after trying a few times.",
      scenario: "I would try to get everyone together for a meeting and talk about what's going on. I'd ask the person who hasn't been working if they need help. For the disagreement, I'd suggest we vote on the direction. The most important thing is communicating clearly and making sure everyone knows what they need to do.",
    },
    emerging: {
      reading_passage: "The town changed because of new buildings. Some people like it some don't. Prices went up.",
      short_response: "I changed my mind about a movie. My friend said it was good so I watched it and it was actually ok.",
      extended_writing: "My school would be different. No boring classes. More hands on stuff. Better lunch. Less tests. Nicer teachers who don't give too much homework.",
      reflection: "I dont really know. I just try again I guess. Or I ask someone.",
      scenario: "I would tell them to do their work. If they dont then the teacher should know. I would just do my part and not worry about it.",
    },
  },
  "9-11": {
    thriving: {
      reading_passage: "The passage presents a nuanced case study in the economics of urban renewal, where the metrics of success depend entirely on the stakeholder you ask. For residents who stayed through the mill closures, the 22% property value increase represents both vindication and threat — their loyalty is rewarded on paper but may price them out in practice. The entrepreneurs brought economic vitality (40 businesses, community programs) but the loss of three longstanding Main Street businesses reveals the unequal distribution of that vitality. The author's framing through the final question — 'revitalized or replaced?' — suggests these aren't mutually exclusive. The evidence supports a more complex reading: River City is being simultaneously revitalized in aggregate and replaced at the individual level.",
      short_response: "My perspective on competitive academic environments shifted after spending a semester at a school with collaborative grading. I had always assumed competition drove excellence, but watching students share strategies openly — without fear of losing their ranking — produced work that was more creative and rigorous than anything I'd seen in ranked environments. The insight wasn't that competition is wrong, but that it optimizes for a narrower definition of excellence than collaboration does.",
      extended_writing: "A well-designed school would recognize that the industrial model of education — synchronous schedules, age-based cohorts, standardized assessment — was optimized for a world that no longer exists. The fundamental redesign I'd propose centers on three principles: agency, integration, and authentic assessment. Agency means students have meaningful choice in what they study and how they demonstrate mastery. Not unlimited choice — there are core competencies everyone needs — but enough autonomy that learning feels like a partnership rather than compliance. Integration means abandoning artificial subject boundaries. A deep investigation into climate change encompasses chemistry, economics, statistics, ethics, and persuasive writing — separating these into different classrooms actually makes each harder to learn. Authentic assessment means evaluating what students can do with knowledge, not what they can recall under timed conditions.",
      reflection: "I've developed a metacognitive framework that I think of as 'productive confusion management.' When I hit a conceptual wall, my first instinct is to identify whether the confusion is about the mechanics (I don't know how to do this) or the meaning (I don't understand why this works). Mechanical confusion responds to practice and examples. Conceptual confusion requires me to step back and examine my assumptions — usually I'm trying to fit new information into an old mental model that doesn't accommodate it. The breakthrough comes when I'm willing to rebuild the model rather than force the information.",
      scenario: "The group dynamics described here reflect a common pattern where unresolved tension creates cascading dysfunction. I'd address each person's concern individually before attempting a group solution. With the non-contributor: a private, non-judgmental check-in. 'I noticed you haven't been as involved — is everything okay? Is there a part of the project that interests you more?' With the dissenter: genuine engagement with their alternative vision. 'Walk me through your approach — what would the end product look like?' Often dissent contains valid critique that the group dismissed too quickly. With the stressed member: acknowledge that the impulse to divide and conquer comes from a reasonable place, but suggest that 15 minutes of structured planning now will save hours of confusion later.",
    },
    developing: {
      reading_passage: "The passage shows a conflict between economic development and preserving the existing community. The new mixed-use space brought benefits like 40 businesses and a farmers market, but caused property values to rise 22% and forced out three longtime businesses. Both sides have legitimate concerns — the town needed economic recovery but not at the cost of pushing out the people who endured the hard years.",
      short_response: "I changed my perspective on social media after reading about its design. I used to think people who spent too much time on their phones were just undisciplined, but learning about how apps are specifically engineered to be addictive made me realize it's more complicated than willpower.",
      extended_writing: "An improved school system would balance structure with flexibility. Core subjects would still be required but taught through more project-based methods. Students would have advisory periods where a dedicated teacher helps them set goals and reflect on progress. Assessment would combine traditional tests with portfolios and presentations. The school day would include dedicated time for independent study and collaboration.",
      reflection: "When I encounter difficult material, I try to break it into smaller pieces and tackle each one separately. I'm better at learning through discussion than reading alone, so I often try to study with someone. I've noticed I sometimes avoid subjects I find hard, which isn't a great strategy. I'm working on being more comfortable with not understanding things immediately.",
      scenario: "I'd suggest the group have an honest conversation about expectations. I'd address the non-contributor directly but tactfully, and try to find a compromise between the two different directions. The key is making sure everyone commits to a plan and follows through.",
    },
    emerging: {
      reading_passage: "The passage is about a town that changed. New businesses came in and that was good but also bad because rent went up. Its complicated.",
      short_response: "I guess I changed my mind about trying new things. I used to not want to but now I sometimes do.",
      extended_writing: "School should be more practical. We learn things we never use. It should teach us about money and real life stuff. Less memorization more doing things. The schedule is too long and we should start later.",
      reflection: "Honestly I usually just move on if I don't get something. Sometimes I google it. I don't really have a strategy.",
      scenario: "I'd probably just do my part and hope it works out. Maybe tell the teacher if things get really bad. Group projects are always like this.",
    },
  },
};
