/**
 * Seed Portuguese task templates for EduInsights
 * Usage: DOTENV_CONFIG_PATH=.env.pt npx tsx scripts/seed-pt-tasks.ts
 */
import { createClient } from "@supabase/supabase-js";
import { config } from "dotenv";

config({ path: ".env.pt" });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

async function run() {
  // Get the tenant
  const { data: tenants } = await supabase.from("tenants").select("id, name");
  const tenant = tenants?.[0];
  if (!tenant) { console.log("No tenant found"); process.exit(1); }
  console.log(`Seeding tasks for: ${tenant.name} (${tenant.id})`);

  const tid = tenant.id;

  const templates = [
    // Grade 8
    { tenant_id: tid, grade_band: "8", task_type: "reading_passage", title: "A Decisão de Rio Verde", language: "pt", difficulty_level: 1, estimated_minutes: 8, dimension_targets: ["reading", "reasoning"], content: { passage: "Rio Verde fica na junção de dois rios que moldaram sua identidade por mais de um século. Os moradores mais antigos lembram quando as fábricas têxteis ocupavam as margens, empregando quase metade da cidade. Quando as fábricas fecharam nos anos 1990, muitas famílias foram embora. As lojas ficaram vazias. O rio, antes fonte de sustento, tornou-se uma lembrança do que foi perdido.\n\nEntão, cinco anos atrás, um grupo de jovens empreendedores propôs converter os prédios abandonados das fábricas em um espaço comunitário de uso misto — parte laboratório maker, parte espaço de coworking, parte cozinha comunitária. A câmara municipal ficou dividida. Alguns viram como exatamente o recomeço que Rio Verde precisava. Outros temiam que atrairia pessoas de fora, aumentaria os impostos e expulsaria as famílias que ficaram durante os anos difíceis.\n\nO projeto seguiu em frente. Hoje, as fábricas convertidas abrigam 40 pequenos negócios, uma feira de agricultores nos fins de semana e um programa gratuito para crianças. Os valores dos imóveis subiram 22%. Mas os aluguéis também. Três negócios tradicionais fecharam, incapazes de pagar os novos contratos. O debate continua: Rio Verde está sendo revitalizada — ou está sendo substituída?", prompt: "Com base na passagem, explique a principal tensão em Rio Verde. Que evidências do texto apoiam ambos os lados do debate?", hints: ["Pense no que diferentes grupos de pessoas em Rio Verde poderiam querer.", "Procure números ou fatos específicos na passagem que apoiem cada ponto de vista."] }, is_active: true },
    { tenant_id: tid, grade_band: "8", task_type: "short_response", title: "Uma Perspectiva Diferente", language: "pt", difficulty_level: 1, estimated_minutes: 5, dimension_targets: ["reasoning", "reflection"], content: { prompt: "Pense em uma vez em que você mudou de ideia sobre algo depois de ouvir um ponto de vista diferente. O que aconteceu e o que fez você reconsiderar?", hints: ["Pode ser algo pequeno — como mudar sua opinião sobre um filme, uma comida ou uma regra da escola."] }, is_active: true },
    { tenant_id: tid, grade_band: "8", task_type: "extended_writing", title: "A Escola Ideal", language: "pt", difficulty_level: 2, estimated_minutes: 10, dimension_targets: ["writing", "reasoning"], content: { prompt: "Se você pudesse projetar a escola perfeita, como ela seria? Pense no horário, nas matérias, em como a aprendizagem acontece e como alunos e professores interagem. Escreva uma descrição detalhada." }, is_active: true },
    { tenant_id: tid, grade_band: "8", task_type: "reflection", title: "Como Você Aprende Melhor", language: "pt", difficulty_level: 1, estimated_minutes: 5, dimension_targets: ["reflection", "persistence"], content: { prompt: "Quando você está tentando entender algo difícil, o que você geralmente faz? Descreva sua abordagem — você relê, faz perguntas, tenta exemplos, faz uma pausa ou algo diferente?" }, is_active: true },
    { tenant_id: tid, grade_band: "8", task_type: "scenario", title: "O Trabalho em Grupo", language: "pt", difficulty_level: 2, estimated_minutes: 7, dimension_targets: ["reasoning", "support_seeking"], content: { scenario: "Você está trabalhando em um projeto em grupo com três colegas. O projeto é para a semana que vem. Um membro do grupo quase não fez nada e não responde às mensagens. Outro discorda da direção escolhida e quer recomeçar. O terceiro está estressado e quer simplesmente dividir tudo e trabalhar separadamente.", prompts: ["O que você faria nesta situação? Explique seu raciocínio passo a passo.", "O que é mais importante acertar quando se trabalha em grupo sob pressão?"] }, is_active: true },
    { tenant_id: tid, grade_band: "8", task_type: "quantitative_reasoning", title: "A Venda de Bolos", language: "pt", difficulty_level: 2, estimated_minutes: 6, dimension_targets: ["reasoning", "persistence"], content: { problem: "A turma do 8º ano está vendendo bolos para arrecadar dinheiro para uma excursão. Cada bolo custa R$30 para fazer e é vendido por R$50. A turma também pagou R$375 pelo aluguel da barraca.\n\nEles venderam 35 bolos até agora.", prompt: "Quanto lucro a turma obteve até agora? Selecione sua resposta e mostre seu trabalho.", choices: ["R$325", "R$700", "Prejuízo de R$325", "R$1.375"] }, is_active: true },
    { tenant_id: tid, grade_band: "8", task_type: "pattern_logic", title: "Padrão Numérico", language: "pt", difficulty_level: 1, estimated_minutes: 4, dimension_targets: ["reasoning"], content: { pattern: "2, 6, 18, 54, ___, ___", prompt: "Quais são os próximos dois números nesta sequência?" }, is_active: true },

    // Grade 6-7
    { tenant_id: tid, grade_band: "6-7", task_type: "reading_passage", title: "O Novo Playground", language: "pt", difficulty_level: 1, estimated_minutes: 7, dimension_targets: ["reading", "reasoning"], content: { passage: "Na primavera passada, a cidade de Vale Verde decidiu reconstruir o playground antigo perto da escola. Os equipamentos estavam enferrujados e alguns balanços estavam quebrados. A cidade fez uma reunião para decidir como seria o novo playground.\n\nAlguns pais queriam um design simples com balanços, escorregador e barras — como o antigo. Eles disseram que as crianças só precisam de ar fresco e espaço para correr. Outros pais queriam algo maior com um muro de escalada, área aquática e trilha na natureza.\n\nA cidade tinha R$250.000 para gastar. O design simples custava R$150.000 e o maior R$375.000. No final, escolheram uma opção intermediária por R$240.000 que incluía o muro de escalada e novos balanços, mas sem a área aquática.", prompt: "Por que a cidade escolheu a opção do meio? Use detalhes da passagem para explicar se você acha que foi uma boa decisão." }, is_active: true },
    { tenant_id: tid, grade_band: "6-7", task_type: "short_response", title: "Um Momento Surpreendente", language: "pt", difficulty_level: 1, estimated_minutes: 5, dimension_targets: ["writing", "reflection"], content: { prompt: "Conte-nos sobre uma vez em que algo te surpreendeu — talvez algo que você aprendeu, viu ou viveu que não esperava. O que aconteceu e por que foi surpreendente?" }, is_active: true },
    { tenant_id: tid, grade_band: "6-7", task_type: "extended_writing", title: "Meu Dia Perfeito", language: "pt", difficulty_level: 1, estimated_minutes: 8, dimension_targets: ["writing", "reasoning"], content: { prompt: "Descreva seu dia perfeito da manhã até a noite. Onde você está? Quem está com você? O que você faz? Seja o mais detalhado possível — nos ajude a imaginar!" }, is_active: true },
    { tenant_id: tid, grade_band: "6-7", task_type: "reflection", title: "Quando as Coisas São Difíceis", language: "pt", difficulty_level: 1, estimated_minutes: 5, dimension_targets: ["reflection", "persistence"], content: { prompt: "Pense em uma vez em que você teve que fazer algo que pareceu muito difícil. O que tornou difícil? O que você fez para superar?" }, is_active: true },

    // Grade 9-11
    { tenant_id: tid, grade_band: "9-11", task_type: "reading_passage", title: "A Questão da Automação", language: "pt", difficulty_level: 2, estimated_minutes: 10, dimension_targets: ["reading", "reasoning"], content: { passage: "Em 2023, uma empresa de logística de médio porte no Brasil substituiu 60% de sua equipe de triagem no armazém por sistemas automatizados. A produtividade aumentou 35% e as taxas de erro caíram para quase zero. A empresa reinvestiu as economias em salários mais altos para os trabalhadores restantes e em um programa de requalificação.\n\nDos 200 trabalhadores deslocados, 45 se inscreveram no programa de requalificação. Destes, 30 concluíram e foram alocados em novos cargos — principalmente em manutenção de sistemas e supervisão de qualidade — com salários 15% mais altos que suas posições anteriores. Os 155 restantes receberam pacotes de indenização equivalentes a 3 meses de salário.\n\nUm estudo de acompanhamento seis meses depois descobriu que 40% dos trabalhadores deslocados encontraram emprego comparável em outro lugar, 25% aceitaram trabalhos com salários mais baixos e 35% permaneceram desempregados. O valor das ações da empresa subiu 18% no mesmo período.", prompt: "Avalie a afirmação de que a automação neste caso foi positiva no geral. Considere as evidências para múltiplas partes interessadas e identifique quais informações fortaleceriam ou enfraqueceriam o argumento." }, is_active: true },
    { tenant_id: tid, grade_band: "9-11", task_type: "extended_writing", title: "Um Sistema que Você Mudaria", language: "pt", difficulty_level: 2, estimated_minutes: 12, dimension_targets: ["writing", "reasoning", "reflection"], content: { prompt: "Identifique um sistema, processo ou instituição que você acredita que não está funcionando tão bem quanto poderia (pode ser na sua escola, na sua comunidade ou na sociedade). Descreva o problema claramente, explique por que persiste e proponha uma mudança realista. Considere possíveis objeções à sua proposta." }, is_active: true },
    { tenant_id: tid, grade_band: "9-11", task_type: "reflection", title: "Crescimento Intelectual", language: "pt", difficulty_level: 2, estimated_minutes: 6, dimension_targets: ["reflection", "persistence"], content: { prompt: "Descreva uma crença ou suposição que você tinha que mudou significativamente ao longo do tempo. O que causou a mudança? Como você pensa sobre esse assunto de forma diferente agora?" }, is_active: true },
    { tenant_id: tid, grade_band: "9-11", task_type: "scenario", title: "O Comitê de Ética", language: "pt", difficulty_level: 3, estimated_minutes: 8, dimension_targets: ["reasoning", "support_seeking"], content: { scenario: "Você faz parte de um comitê de ética estudantil. Um colega foi pego usando uma ferramenta de IA para escrever uma parte significativa de sua redação de vestibular. O aluno argumenta que usou a IA como ponto de partida e editou substancialmente. O texto original gerado pela IA e a versão final mostram cerca de 40% de sobreposição. O código de honra da escola proíbe 'enviar trabalhos que não sejam seus', mas não menciona especificamente ferramentas de IA.", prompts: ["Que recomendação você faria ao comitê e por quê?", "Como a escola deveria atualizar seu código de honra para lidar com esse tipo de situação?"] }, is_active: true },

    // === PROBLEMAS DE MATEMÁTICA — 6º-7º ANO (3 variantes) ===
    { tenant_id: tid, grade_band: "6-7", task_type: "math_problem", title: "O Orçamento da Excursão", language: "pt", difficulty_level: 1, estimated_minutes: 6, dimension_targets: ["math", "reasoning"], content: { problem: "Sua turma está planejando uma excursão. Vão 28 alunos e 4 adultos. Os ingressos custam R$8 para alunos e R$12 para adultos. O ônibus custa R$180 pela ida e volta. A escola já arrecadou R$150 em uma feira de doces.\n\nQuanto dinheiro a turma ainda precisa arrecadar?", prompt: "Mostre seu trabalho passo a passo. Explique como você chegou à resposta.", hints: ["Primeiro calcule o custo total dos ingressos, depois some o custo do ônibus.", "Total necessário = (28 × R$8) + (4 × R$12) + R$180. Depois subtraia R$150."] }, is_active: true },
    { tenant_id: tid, grade_band: "6-7", task_type: "math_problem", title: "A Feira de Doces", language: "pt", difficulty_level: 1, estimated_minutes: 6, dimension_targets: ["math", "reasoning"], content: { problem: "A turma do 6º ano está fazendo uma feira de doces. Eles fizeram 48 cupcakes vendidos a R$2 cada, 30 brownies a R$3 cada e 24 biscoitos a R$1,50 cada. No final da feira, venderam todos os cupcakes, 22 brownies e 18 biscoitos.\n\nOs ingredientes custaram R$65 no total.", prompt: "Quanto lucro a turma teve? Mostre todo o seu trabalho e explique cada passo.", hints: ["Calcule a receita de cada item vendido e some os valores.", "Receita = (48 × R$2) + (22 × R$3) + (18 × R$1,50). Lucro = Receita - R$65."] }, is_active: true },
    { tenant_id: tid, grade_band: "6-7", task_type: "math_problem", title: "A Horta da Escola", language: "pt", difficulty_level: 1, estimated_minutes: 6, dimension_targets: ["math", "reasoning"], content: { problem: "Uma horta retangular da escola mede 12 metros por 8 metros. Os alunos querem cercar a horta e dividi-la em 3 seções iguais com cercas atravessando o lado curto (8 metros).\n\nO metro de cerca custa R$4,50.", prompt: "Quantos metros de cerca eles precisam no total e quanto vai custar? Mostre seu trabalho e explique seu raciocínio.", hints: ["Faça um desenho primeiro. O perímetro precisa de cerca, mais 2 cercas divisórias por dentro.", "Perímetro = 2(12) + 2(8) = 40 metros. Mais 2 divisórias × 8 metros = 16 metros. Total = 56 metros."] }, is_active: true },

    // === PROBLEMAS DE MATEMÁTICA — 8º ANO (3 variantes) ===
    { tenant_id: tid, grade_band: "8", task_type: "math_problem", title: "A Loja da Escola", language: "pt", difficulty_level: 2, estimated_minutes: 7, dimension_targets: ["math", "reasoning"], content: { problem: "A loja da escola vende cadernos por R$3,50 cada e canetas por R$1,25 cada. Durante a Semana da Escola, tudo está com 20% de desconto. A loja também cobra 6% de imposto sobre o preço com desconto.\n\nMaria quer comprar 4 cadernos e 6 canetas.", prompt: "Quanto Maria vai pagar no total? Mostre cada passo do seu cálculo e explique seu raciocínio.", hints: ["Primeiro encontre o total original, depois aplique o desconto de 20% e por fim adicione o imposto de 6%.", "Original: (4 × R$3,50) + (6 × R$1,25) = ? Depois multiplique por 0,80 (desconto). Depois multiplique por 1,06 (imposto)."] }, is_active: true },
    { tenant_id: tid, grade_band: "8", task_type: "math_problem", title: "A Festa de Pizza", language: "pt", difficulty_level: 2, estimated_minutes: 7, dimension_targets: ["math", "reasoning"], content: { problem: "Uma turma de 32 alunos vai pedir pizza. Cada pizza grande tem 8 fatias e custa R$59,90. Cada aluno come em média 2,5 fatias. O professor adiciona 10% de gorjeta sobre o subtotal antes do imposto, e depois 7% de imposto é aplicado ao subtotal (antes da gorjeta).\n\nA turma arrecadou R$640 dos alunos.", prompt: "Quantas pizzas eles precisam? Qual é o custo total incluindo gorjeta e imposto? R$640 é suficiente? Mostre todo o trabalho.", hints: ["Total de fatias = 32 × 2,5. Divida por 8 e arredonde para cima para obter pizzas inteiras.", "Pizzas necessárias × R$59,90 = subtotal. Imposto = subtotal × 0,07. Gorjeta = subtotal × 0,10. Total = subtotal + imposto + gorjeta."] }, is_active: true },
    { tenant_id: tid, grade_band: "8", task_type: "math_problem", title: "A Competição de Atletismo", language: "pt", difficulty_level: 2, estimated_minutes: 7, dimension_targets: ["math", "reasoning"], content: { problem: "Em uma competição de atletismo, o Corredor A completa uma volta de 400m em 58,4 segundos. O Corredor B completa a mesma volta em 1 minuto e 2,7 segundos. O Corredor C é 15% mais lento que o Corredor A.\n\nA equipe de revezamento precisa de 3 corredores cujo tempo combinado para 3 voltas seja menor que 3 minutos.", prompt: "Calcule o tempo de cada corredor. Alguma combinação desses 3 corredores forma uma equipe de revezamento que termina em menos de 3 minutos? Mostre seu raciocínio.", hints: ["Converta todos os tempos em segundos primeiro. Corredor C = tempo do Corredor A × 1,15.", "3 minutos = 180 segundos. Tente todas as combinações: A+B+C, e verifique o total."] }, is_active: true },

    // === PROBLEMAS DE MATEMÁTICA — 9º-11º ANO (3 variantes) ===
    { tenant_id: tid, grade_band: "9-11", task_type: "math_problem", title: "O Fundo de Bolsas", language: "pt", difficulty_level: 3, estimated_minutes: 8, dimension_targets: ["math", "reasoning"], content: { problem: "O fundo de bolsas de uma escola começa com R$50.000 e rende 4,5% de juros anuais, com capitalização anual. A cada ano, a escola concede R$4.000 em bolsas a partir do fundo.\n\nO fundo segue este padrão a cada ano:\n1. Os juros são adicionados ao saldo atual\n2. Em seguida R$4.000 são subtraídos para as bolsas", prompt: "Calcule o saldo do fundo após o Ano 1, Ano 2 e Ano 3. O fundo eventualmente vai zerar, crescer indefinidamente ou se estabilizar? Explique seu raciocínio matemático.", hints: ["Ano 1: (R$50.000 × 1,045) - R$4.000 = ?", "Compare os juros ganhos a cada ano com os R$4.000 retirados. O que acontece à medida que o saldo muda?"] }, is_active: true },
    { tenant_id: tid, grade_band: "9-11", task_type: "math_problem", title: "O Modelo Populacional", language: "pt", difficulty_level: 3, estimated_minutes: 8, dimension_targets: ["math", "reasoning"], content: { problem: "Uma cidade pequena tem população de 12.000 habitantes. Está crescendo a 3% ao ano. Uma cidade vizinha tem população de 45.000, mas está em declínio a 1,5% ao ano.\n\nSuponha que essas taxas permaneçam constantes.", prompt: "Em quantos anos a população da cidade pequena vai ultrapassar metade da população da cidade vizinha? Mostre seus cálculos para pelo menos 5 anos e explique o padrão que você observa.", hints: ["Cidade pequena após n anos = 12.000 × (1,03)^n. Cidade vizinha após n anos = 45.000 × (0,985)^n.", "Calcule as duas populações ano a ano e compare. Quando a Cidade Pequena > Cidade Vizinha / 2?"] }, is_active: true },
    { tenant_id: tid, grade_band: "9-11", task_type: "math_problem", title: "O Preço dos Ingressos", language: "pt", difficulty_level: 3, estimated_minutes: 8, dimension_targets: ["math", "reasoning"], content: { problem: "O teatro da escola tem 500 lugares. No ano passado, os ingressos custavam R$30 cada e foram vendidos 420 lugares. Pesquisas sugerem que para cada R$2 de aumento no preço, 20 ingressos a menos serão vendidos. Para cada R$2 de redução, 20 ingressos a mais serão vendidos (até o limite da lotação).\n\nA produção custa R$8.000 independentemente da presença de público.", prompt: "Que preço de ingresso maximiza o lucro? Qual é o lucro máximo? Mostre seu raciocínio matemático, incluindo quaisquer equações ou modelos que você usar.", hints: ["Seja x a variação no número de aumentos/reduções de R$2. Receita = (30 + 2x)(420 - 20x). Lucro = Receita - 8000.", "Expanda a equação da receita e encontre seu máximo. É uma quadrática — o vértice dá o máximo."] }, is_active: true },
  ];

  const { error } = await supabase.from("task_templates").insert(templates);
  if (error) {
    console.error("Error:", error.message);
  } else {
    console.log(`Seeded ${templates.length} Portuguese task templates`);
  }
}

run().then(() => process.exit());
