export const dynamic = "force-dynamic";
import { NextRequest, NextResponse } from "next/server";

import { supabaseAdmin } from "@/lib/supabase/admin";
import { writeAuditLog } from "@/lib/audit";
import { requireFeature } from "@/lib/licensing/gate";
import { handleLicenseError } from "@/lib/licensing/apiHandler";
import { FEATURES } from "@/lib/licensing/features";

export async function GET(req: NextRequest) {
  const { createClient } = await import("@/lib/supabase/server");
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { searchParams } = new URL(req.url);
  const candidateId = searchParams.get("candidate_id");
  const exportType = searchParams.get("export_type") as "internal" | "family_summary";
  const language = (searchParams.get("language") ?? "en") as "en" | "pt";

  if (!candidateId || !exportType) {
    return NextResponse.json({ error: "candidate_id and export_type required" }, { status: 400 });
  }

  // Get data
  const { data: candidate } = await supabaseAdmin
    .from("candidates")
    .select("*, tenants(name)")
    .eq("id", candidateId)
    .single();

  if (!candidate) return NextResponse.json({ error: "Not found" }, { status: 404 });

  // License gate: Portuguese reports require Professional tier
  if (language === "pt") {
    try {
      await requireFeature(candidate.tenant_id, FEATURES.PORTUGUESE_REPORTS);
    } catch (err) {
      const licenseResponse = handleLicenseError(err);
      if (licenseResponse) return licenseResponse;
      throw err;
    }
  }

  const tenant = candidate.tenants as unknown as { name: string };

  const { data: profile } = await supabaseAdmin
    .from("insight_profiles")
    .select("*")
    .eq("candidate_id", candidateId)
    .eq("is_final", true)
    .order("generated_at", { ascending: false })
    .limit(1)
    .single();

  const { data: review } = await supabaseAdmin
    .from("evaluator_reviews")
    .select("*, users(full_name)")
    .eq("candidate_id", candidateId)
    .eq("status", "finalized")
    .order("finalized_at", { ascending: false })
    .limit(1)
    .single();

  // Learning support signals
  let lsSignal: Record<string, unknown> | null = null;
  if (profile?.learning_support_signal_id) {
    const { data } = await supabaseAdmin
      .from("learning_support_signals")
      .select("*")
      .eq("id", profile.learning_support_signal_id)
      .single();
    lsSignal = data;
  }

  const isEn = language === "en";
  const disclaimer = isEn
    ? "This report is generated by LIFT, a non-diagnostic admissions insight platform. It does not diagnose any clinical, medical, or learning condition. All final decisions are made by qualified human reviewers."
    : "Este relatório é gerado pelo LIFT, uma plataforma de insights de admissão não-diagnóstica. Não diagnostica nenhuma condição clínica, médica ou de aprendizagem. Todas as decisões finais são feitas por revisores humanos qualificados.";

  const date = new Date().toLocaleDateString(isEn ? "en-US" : "pt-BR", {
    year: "numeric", month: "long", day: "numeric",
  });

  let html: string;

  if (exportType === "internal") {
    const dims = [
      { label: isEn ? "Reading" : "Leitura", score: profile?.reading_score },
      { label: isEn ? "Writing" : "Escrita", score: profile?.writing_score },
      { label: isEn ? "Reasoning" : "Raciocínio", score: profile?.reasoning_score },
      { label: isEn ? "Reflection" : "Reflexão", score: profile?.reflection_score },
      { label: isEn ? "Persistence" : "Persistência", score: profile?.persistence_score },
      { label: isEn ? "Support Seeking" : "Busca de Apoio", score: profile?.support_seeking_score },
    ];

    const reviewerName = (review?.users as { full_name: string } | null)?.full_name ?? "";
    const flags = [...(profile?.low_confidence_flags as string[] ?? []), ...(profile?.unusual_pattern_flags as string[] ?? [])];

    html = `<!DOCTYPE html><html lang="${language}"><head><meta charset="UTF-8">
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; max-width: 700px; margin: 0 auto; padding: 40px 30px; color: #1a1a2e; font-size: 13px; line-height: 1.6; }
  h1 { color: #6366f1; margin: 0; font-size: 24px; }
  .disclaimer { background: #fff3cd; border: 1px solid #ffc107; padding: 10px 14px; border-radius: 6px; font-size: 11px; margin: 16px 0; }
  .meta { color: #666; font-size: 12px; margin: 8px 0; }
  .score-row { display: flex; align-items: center; margin: 6px 0; }
  .score-label { width: 140px; }
  .score-bar { flex: 1; height: 16px; background: #e8e8f0; border-radius: 8px; overflow: hidden; }
  .score-fill { height: 100%; border-radius: 8px; }
  .score-val { width: 40px; text-align: right; font-weight: bold; }
  .green { background: #10b981; } .amber { background: #f59e0b; } .red { background: #f43f5e; }
  .section { margin: 24px 0; }
  .section h2 { font-size: 16px; border-bottom: 1px solid #e0e0e0; padding-bottom: 4px; }
  .flag { display: inline-block; background: #fff3cd; border: 1px solid #ffc107; padding: 2px 8px; border-radius: 12px; font-size: 11px; margin: 2px; }
  .footer { margin-top: 40px; border-top: 1px solid #e0e0e0; padding-top: 10px; font-size: 10px; color: #999; text-align: center; }
  @media print { body { padding: 20px; } .disclaimer { break-inside: avoid; } }
</style></head><body>
<h1>LIFT</h1>
<p class="meta">${tenant.name} · ${isEn ? "Internal Admissions Report" : "Relatório Interno de Admissão"}</p>
<p class="meta">${isEn ? "Candidate" : "Candidato"}: <strong>${candidate.first_name} ${candidate.last_name}</strong> · ${isEn ? "Grade" : "Série"} ${candidate.grade_applying_to} · ${date}</p>
<div class="disclaimer">${disclaimer}</div>

${profile?.tri_score != null ? `<div class="section" style="text-align: center; padding: 20px; border: 2px solid ${
  profile.tri_label === "thriving" ? "#10b981" : profile.tri_label === "ready" ? "#6366f1" : profile.tri_label === "developing" ? "#f59e0b" : "#f43f5e"
}; border-radius: 12px;">
<p style="font-size: 11px; color: #999; text-transform: uppercase; letter-spacing: 1px;">${isEn ? "Transition Readiness Index" : "Índice de Prontidão para Transição"}</p>
<p style="font-size: 36px; font-weight: bold; color: ${
  profile.tri_label === "thriving" ? "#10b981" : profile.tri_label === "ready" ? "#6366f1" : profile.tri_label === "developing" ? "#f59e0b" : "#f43f5e"
}; margin: 8px 0;">${Number(profile.tri_score).toFixed(1)}</p>
<p style="font-size: 16px; font-weight: 600; text-transform: capitalize;">${profile.tri_label}</p>
${profile.tri_summary ? `<p style="font-size: 13px; color: #666; margin-top: 8px;">${profile.tri_summary}</p>` : ""}
<p style="font-size: 11px; color: #999; margin-top: 4px;">${isEn ? "Confidence" : "Confiança"}: ${profile.tri_confidence ?? "—"}</p>
</div>` : ""}

<div class="section"><h2>${isEn ? "Dimension Scores" : "Pontuações por Dimensão"}</h2>
${dims.map((d) => {
  const val = d.score != null ? Math.round(Number(d.score)) : 0;
  const cls = val >= 70 ? "green" : val >= 40 ? "amber" : "red";
  return `<div class="score-row"><span class="score-label">${d.label}</span><div class="score-bar"><div class="score-fill ${cls}" style="width:${val}%"></div></div><span class="score-val">${d.score != null ? val : "—"}</span></div>`;
}).join("")}
<p class="meta">${isEn ? "Overall Confidence" : "Confiança Geral"}: ${profile?.overall_confidence ?? "—"}%</p>
</div>

${flags.length > 0 ? `<div class="section"><h2>${isEn ? "Caution Flags" : "Sinais de Atenção"}</h2>${flags.map((f) => `<span class="flag">${f.replace(/_/g, " ")}</span>`).join(" ")}</div>` : ""}

${profile?.internal_narrative ? `<div class="section"><h2>${isEn ? "Narrative Analysis" : "Análise Narrativa"}</h2><div style="white-space:pre-wrap">${profile.internal_narrative}</div></div>` : ""}

${profile?.placement_guidance ? `<div class="section"><h2>${isEn ? "Placement Guidance" : "Orientação de Colocação"}</h2><div style="white-space:pre-wrap">${profile.placement_guidance}</div></div>` : ""}

${review ? `<div class="section"><h2>${isEn ? "Evaluator Decision" : "Decisão do Avaliador"}</h2>
<p><strong>${isEn ? "Recommendation" : "Recomendação"}:</strong> ${(review.recommendation_tier as string)?.replace(/_/g, " ") ?? "—"}</p>
${review.notes ? `<p><strong>${isEn ? "Notes" : "Notas"}:</strong> ${review.notes}</p>` : ""}
${review.override_reason ? `<p><strong>${isEn ? "Override Reason" : "Razão da Substituição"}:</strong> ${review.override_reason}</p>` : ""}
<p class="meta">${reviewerName} · ${review.finalized_at ? new Date(review.finalized_at as string).toLocaleDateString() : ""}</p>
</div>` : ""}

${lsSignal && lsSignal.support_indicator_level !== "none" ? `<div class="section" style="border: 2px solid ${lsSignal.support_indicator_level === "recommend_screening" ? "#f43f5e" : "#f59e0b"}; border-radius: 8px; padding: 16px;">
<h2>${isEn ? "Learning Support Indicators" : "Indicadores de Apoio à Aprendizagem"}</h2>
<p style="font-size: 11px; color: #666; margin-bottom: 12px;">${isEn ? "These patterns do not constitute a diagnosis. They indicate behavioral signals that may suggest a student would benefit from a learning support evaluation." : "Esses padrões não constituem um diagnóstico. Eles indicam sinais comportamentais que podem sugerir que o aluno se beneficiaria de uma avaliação de apoio à aprendizagem."}</p>
<ul style="margin: 8px 0;">
${lsSignal.high_revision_depth ? `<li>${isEn ? "Extended revision and editing patterns in written responses" : "Padrões extensos de revisão e edição em respostas escritas"}</li>` : ""}
${lsSignal.low_reading_dwell ? `<li>${isEn ? "Reading pace relative to passage length warrants follow-up" : "Ritmo de leitura em relação ao tamanho do texto requer acompanhamento"}</li>` : ""}
${lsSignal.short_written_output ? `<li>${isEn ? "Written output is notably brief relative to task expectations" : "Produção escrita notavelmente breve em relação às expectativas da tarefa"}</li>` : ""}
${lsSignal.high_response_latency ? `<li>${isEn ? "Consistently extended response time across all task types" : "Tempo de resposta consistentemente prolongado em todos os tipos de tarefa"}</li>` : ""}
${lsSignal.task_abandonment_pattern ? `<li>${isEn ? "Frequent task revisits and return patterns" : "Padrões frequentes de revisita e retorno às tarefas"}</li>` : ""}
${lsSignal.hint_seeking_high ? `<li>${isEn ? "High frequency of hint and support requests" : "Alta frequência de solicitações de dicas e suporte"}</li>` : ""}
${lsSignal.planning_task_difficulty ? `<li>${isEn ? "Difficulty structuring multi-step planning tasks" : "Dificuldade em estruturar tarefas de planejamento em múltiplas etapas"}</li>` : ""}
${lsSignal.reasoning_writing_gap ? `<li>${isEn ? "Significant gap between reasoning signals and written expression" : "Lacuna significativa entre sinais de raciocínio e expressão escrita"}</li>` : ""}
</ul>
${lsSignal.evaluator_note ? `<p style="background: ${lsSignal.support_indicator_level === "recommend_screening" ? "#fef2f2" : "#fffbeb"}; border: 1px solid ${lsSignal.support_indicator_level === "recommend_screening" ? "#fecaca" : "#fde68a"}; padding: 8px 12px; border-radius: 6px; font-size: 12px;">${lsSignal.evaluator_note}</p>` : ""}
<p style="font-size: 10px; color: #999; margin-top: 12px;">${isEn ? "LIFT does not diagnose learning disabilities or any clinical condition. These indicators are for school use only and must be reviewed by a qualified professional before any action is taken." : "LIFT não diagnostica dificuldades de aprendizagem ou qualquer condição clínica. Esses indicadores são apenas para uso escolar e devem ser revisados por um profissional qualificado antes de qualquer ação."}</p>
</div>` : ""}

<div class="footer">${isEn ? "Generated by" : "Gerado por"} LIFT — Inteliflow AI · ${date}<br>${disclaimer}</div>
</body></html>`;
  } else {
    // Family summary
    html = `<!DOCTYPE html><html lang="${language}"><head><meta charset="UTF-8">
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 40px 30px; color: #1a1a2e; font-size: 14px; line-height: 1.7; }
  h1 { color: #6366f1; margin: 0; font-size: 24px; }
  .disclaimer { background: #e8f4fd; border: 1px solid #90cdf4; padding: 12px 16px; border-radius: 6px; font-size: 12px; margin: 16px 0; }
  .meta { color: #666; font-size: 12px; margin: 8px 0; }
  .narrative { margin: 20px 0; white-space: pre-wrap; }
  .footer { margin-top: 40px; border-top: 1px solid #e0e0e0; padding-top: 10px; font-size: 10px; color: #999; text-align: center; }
  @media print { body { padding: 20px; } }
</style></head><body>
<h1>LIFT</h1>
<p class="meta">${tenant.name}</p>
<p class="meta">${isEn ? "Student" : "Aluno(a)"}: <strong>${candidate.first_name} ${candidate.last_name}</strong> · ${date}</p>
<div class="disclaimer">${isEn
  ? "This summary describes how your child approached learning tasks. It is not a diagnosis or prediction."
  : "Este resumo descreve como seu(sua) filho(a) abordou as tarefas de aprendizagem. Não é um diagnóstico ou previsão."}</div>
<div class="narrative">${profile?.family_narrative ?? (isEn ? "Summary not yet available." : "Resumo ainda não disponível.")}</div>
${profile?.tri_summary ? `<p style="margin-top: 16px; font-style: italic; color: #555;">${(profile.tri_summary as string).replace("This student", candidate.first_name as string)}</p>` : ""}
<div class="footer">${isEn ? "Generated by" : "Gerado por"} LIFT — Inteliflow AI · ${date}<br>${disclaimer}</div>
</body></html>`;
  }

  // Store export record
  await supabaseAdmin.from("report_exports").insert({
    candidate_id: candidateId,
    tenant_id: candidate.tenant_id,
    export_type: exportType,
    language,
    generated_by: user.id,
  });

  await writeAuditLog(supabaseAdmin, {
    tenant_id: candidate.tenant_id,
    actor_id: user.id,
    candidate_id: candidateId,
    action: "report_exported",
    payload: { export_type: exportType, language },
  });

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `inline; filename="lift-${exportType}-${candidate.first_name}-${candidate.last_name}-${language}.html"`,
    },
  });
}
